export const catalogShopAbi = [
  {
    type: "event",
    name: "DeliveryExecuted",
    anonymous: false,
    inputs: [
      {indexed: true, name: "contextId", type: "bytes32"},
      {indexed: true, name: "collectionId", type: "uint32"},
      {indexed: true, name: "collection", type: "address"},
      {indexed: false, name: "standard", type: "uint8"},
      {indexed: false, name: "operator", type: "address"},
      {indexed: false, name: "from", type: "address"},
      {indexed: false, name: "to", type: "address"},
      {indexed: false, name: "tokenId", type: "uint256"},
      {indexed: false, name: "amount", type: "uint256"},
      {indexed: false, name: "sourceId", type: "uint256"},
    ],
  },
  {
    type: "event",
    name: "ListingCreated",
    anonymous: false,
    inputs: [{indexed: true, name: "listingId", type: "uint256"}],
  },
  {
    type: "event",
    name: "ListingConfigUpdated",
    anonymous: false,
    inputs: [
      {indexed: true, name: "listingId", type: "uint256"},
      {indexed: false, name: "active", type: "bool"},
      {indexed: false, name: "startsAt", type: "uint64"},
      {indexed: false, name: "endsAt", type: "uint64"},
      {indexed: false, name: "maxPerWallet", type: "uint64"},
      {indexed: false, name: "maxTotalSales", type: "uint64"},
      {indexed: false, name: "sold", type: "uint64"},
      {indexed: false, name: "payoutGroupId", type: "uint32"},
    ],
  },
  {
    type: "event",
    name: "ListingLinesReplaced",
    anonymous: false,
    inputs: [
      {indexed: true, name: "listingId", type: "uint256"},
      {indexed: false, name: "lineCount", type: "uint256"},
      {indexed: false, name: "linesHash", type: "bytes32"},
    ],
  },
  {
    type: "event",
    name: "ListingLineSet",
    anonymous: false,
    inputs: [
      {indexed: true, name: "listingId", type: "uint256"},
      {indexed: true, name: "lineIndex", type: "uint256"},
      {indexed: true, name: "collectionId", type: "uint32"},
      {indexed: false, name: "tokenId", type: "uint256"},
      {indexed: false, name: "amountPerUnit", type: "uint256"},
      {indexed: false, name: "deliveryMode", type: "uint8"},
      {indexed: false, name: "adapterData", type: "bytes"},
    ],
  },
  {
    type: "event",
    name: "ListingDeactivated",
    anonymous: false,
    inputs: [{indexed: true, name: "listingId", type: "uint256"}],
  },
  {
    type: "event",
    name: "ETHPaymentConfigured",
    anonymous: false,
    inputs: [
      {indexed: true, name: "listingId", type: "uint256"},
      {indexed: false, name: "enabled", type: "bool"},
      {indexed: false, name: "price", type: "uint256"},
    ],
  },
  {
    type: "event",
    name: "ERC20PaymentConfigured",
    anonymous: false,
    inputs: [
      {indexed: true, name: "listingId", type: "uint256"},
      {indexed: true, name: "token", type: "address"},
      {indexed: false, name: "enabled", type: "bool"},
      {indexed: false, name: "price", type: "uint256"},
    ],
  },
  {
    type: "event",
    name: "ERC20PaymentConfigCleared",
    anonymous: false,
    inputs: [
      {indexed: true, name: "listingId", type: "uint256"},
      {indexed: true, name: "token", type: "address"},
    ],
  },
] as const;
